---
- name: 安装 Kubernetes 组件
  hosts: all
  become: true

  tasks:
    - name: 安装 kubelet, kubeadm, kubectl
      dnf:
        name:
          - kubelet-1.18.6
          - kubeadm-1.18.6
          - kubectl-1.18.6
        state: present
    - name: Enable 开机启动
      service:
        name: kubelet
        enabled: true
        state: started