---
- name: Copy and Install Docker packages
  hosts: all
  become: yes  # 使用sudo权限执行任务

  tasks:
    - name: 拷贝文件
      copy:
        src: "{{ item }}"
        dest: /tmp/
      with_items:
        - docker-ce-19.03.13-3.el7.x86_64.rpm
        - docker-ce-cli-19.03.13-3.el7.x86_64.rpm
        - containerd.io-1.3.7-3.1.el7.x86_64.rpm

    - name: Install Docker packages
      command: dnf install -y /tmp/{{ item }}
      with_items:
        - docker-ce-19.03.13-3.el7.x86_64.rpm
        - docker-ce-cli-19.03.13-3.el7.x86_64.rpm
        - containerd.io-1.3.7-3.1.el7.x86_64.rpm

    - name: Start Docker service
      systemd:
        name: docker
        state: started  # 启动Docker服务
        enabled: yes  # 设置Docker服务开机自启
